[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  EMAIL_USER = "kesny_toussaint@student.uml.edu"
  EMAIL_PASS = "Mariana4947$$$$$"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200